# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180716_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
