# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_dojos_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='poopy', max_length=1000),
        ),
    ]
